name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: processor
    attributes:
      label: Processor
      options:
        - M1 (or later)
        - M1 Pro (or later)
        - M1 Max (or later)
        - M1 Ultra (or later)
    validations:
      required: true
  - type: dropdown
    id: memory
    attributes:
      label: Memory
      options:
        - 8GB
        - 16GB
        - 32GB
        - 64GB (or higher)
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Provide any steps necessary to reproduce the problem.
    validations:
      required: true
  - type: textarea
    id: crash-logs
    attributes:
      label: Crash Log
      description: If Mochi Diffusion quit unexpectedly, copy the text under Problem Details and System Configuration. This will be automatically formatted, so no need for backticks. You may need to click on `Report...` to see this info.
      render: shell
